GET https://http-practice.herokuapp.com/wilders

###
GET https://http-practice.herokuapp.com/wilders?page=2&language=PHP

###
GET http-practice.herokuapp.com/wilders?language=JavaScript
###
GET http-practice.herokuapp.com/wilders/1941

###
POST https://http-practice.herokuapp.com/wilders
Content-Type: application/x-www-form-urlencoded

name=John%20d'oh&language=PHP

###
POST https://http-practice.herokuapp.com/wilders
Content-Type: application/JSON

{
  "name": "Tar Zan",
  "language": "JavaScript"
}

###
PUT  https://http-practice.herokuapp.com/wilders/1941
Content-Type: application/JSON

{
  "name": "Tar Zan Boy",
  "language": "JavaScript"
}

###
DELETE  https://http-practice.herokuapp.com/wilders/1943

